if(BUILD_UNIT_TESTS)
    include(GoogleTest)
    file(GLOB_RECURSE UCMSTORE_TEST_SOURCE_FILES "./case/*.cc")
    add_executable(ucmstore.test ${UCMSTORE_TEST_SOURCE_FILES})
    target_include_directories(ucmstore.test PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/case)
    target_link_libraries(ucmstore.test PRIVATE
        posixstore cachestore fakestore
        gtest_main gtest gmock
    )
    gtest_discover_tests(ucmstore.test)

    file(GLOB_RECURSE UCMMEMORY_TEST_SOURCE_FILES "./case/memory/*.cc")
    add_executable(ucmmemory.test ${UCMMEMORY_TEST_SOURCE_FILES})
    target_include_directories(ucmmemory.test PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/case)
    target_link_libraries(ucmmemory.test PRIVATE
        memorystore
        storeintf
        gtest_main gtest gmock
    )
    gtest_discover_tests(ucmmemory.test)
endif()
